### ISSUE TITLE
Unable to load asset: AssetManifest.json

### ISSUE THREAD

**Issue by martinburkot** [meta-flutter/meta-flutter#222]
Hello,
I am using a dunfell branch and it seems that the flutter apps are unable to load its assets. I've created simple flutter app containing just one picture and I try to run it, but I always get the "Unable to load asset" exception. I think that the flutter is unable to see its assets, but I don't know why. When I try to run the "flutter_animated_background" app from the "flutter-apps" recipes and use the "Image" instead of shape is also not working. This issue may have the same root cause as the issue #205 that is also occurring on my build. Please let me know if there's anything else I can do to help you solve the issue.

Please see the rest of the issue for more details. 
```
/usr/bin/flutter-client -f -b /usr/share/flutter/img_example/lib
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to load asset: AssetManifest.json
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:258)
<asynchronous suspension>
#1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:83)
<asynchronous suspension>
```
Here is the code of my app:
```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Img example', home: Image.asset('assets/frbul.jpg'));
  }
}
```
And the pubspec.yaml
```
name: img_example
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/frbul.jpg
```
The bundle folder layout looks like this:
```
.
└── img_example
    ├── data
    │   └── flutter_assets
    │       ├── AssetManifest.json
    │       ├── assets
    │       │   └── frbul.jpg
    │       ├── FontManifest.json
    │       ├── isolate_snapshot_data
    │       ├── kernel_blob.bin
    │       ├── NOTICES.Z
    │       ├── packages
    │       │   └── cupertino_icons
    │       │       └── assets
    │       │           └── CupertinoIcons.ttf
    │       ├── shaders
    │       │   └── ink_sparkle.frag
    │       └── vm_snapshot_data
    └── lib
        └── libapp.so

9 directories, 10 files
```

Thank you, Martin
