### ISSUE TITLE
Federated Plugin not loaded in Release buids, works well with Debug

### ISSUE THREAD

**Issue by matsch82** [meta-flutter/meta-flutter#475]
It seems like the bug https://github.com/meta-flutter/meta-flutter/issues/115 is again present in kirkstone branch with 3.19.3 flutter.

I sucessfully integrated the sony elinux camera plugin, it is loaded properly when running with debug, but is not used when running release version:
`LD_LIBRARY_PATH=/usr/share/flutter/3.19.3/debug/lib/ flutter-drm-gbm-backend -b /flutter/cam_example/3.19.3/release/` works while 
`LD_LIBRARY_PATH=/usr/share/flutter/3.19.3/release/lib/ flutter-drm-gbm-backend -b /flutter/cam_example/3.19.3/release/` fails to load the dart platform implementation and does some fallback.

The Plugin uses the following pubspec declaration:
```yaml
dependencies:
  camera_platform_interface: ^2.5.0
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: CameraElinuxPlugin
        dartPluginClass: ELinuxCamera
```
